---
title: "share_or"
output: html_document
---

## read the case and control data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
setwd("~/pfam/analysis_human_pfam/7_hcm")
rm(list=ls())
setwd("./")
source("./or_ci.R")

variant_count <- read.delim("~/pfam/analysis_human_pfam/7_hcm/hrc_share_variant.txt", stringsAsFactors=FALSE)
gnomad_count <- read.delim("~/pfam/analysis_human_pfam/7_hcm/hrc_gnomad_variant.txt", stringsAsFactors=FALSE)
patient_number<-6327
gnomAD_number<-125748
gnomad_count<-subset(gnomad_count,is.na(gnomAD_AF)!=TRUE)
```

## Calculate the OR without any priotisation

```{r or_raw, include=FALSE}

gene_list<-unique(variant_count$Gene)
gene_list
or_raw=data.frame(gene=gene_list)
case_freq_gene<-aggregate(case_freq~Gene,data=variant_count,sum)
or_raw$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$Gene),]$case_freq

gnomAD_freq_gene<-aggregate(gnomAD_AF~Gene,data=gnomad_count,sum)
or_raw$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$Gene),]$gnomAD_AF

or_raw[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(or_raw[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2],predict=NA)}))
#or_raw$or<-or(or_raw$case_freq_gene,or_raw$gnomAD_freq_gene)

or_raw$or<-ifelse((or_raw$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,or(or_raw$case_freq_gene,or_raw$gnomAD_freq_gene))

or_raw$ci_lower<-ifelse((or_raw$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,or_ci_lower(or_raw$case_freq_gene,or_raw$gnomAD_freq_gene,patient_number,gnomAD_number))
or_raw$ci_upper<-ifelse((or_raw$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,or_ci_upper(or_raw$case_freq_gene,or_raw$gnomAD_freq_gene,patient_number,gnomAD_number))


or_raw$log_or<-log(or(or_raw$case_freq_gene,or_raw$gnomAD_freq_gene))
or_raw$se_log_or<-se_log_or(or_raw$case_freq_gene,or_raw$gnomAD_freq_gene,patient_number,gnomAD_number)

sarc_gene<-c("ACTC1","MYBPC3","MYH7","MYL2","MYL3","TNNI3","TNNT2","TPM1")
non_sarc_gene<-c("GLA","LAMP2","LMNA","PRKAG2","TTR")

```

## Calculate the OR when using HMC < 0.8 to classify pathogenic variants

```{r pathogenic_novel, include=FALSE}
## or with pathogenicity pathogenic prediction excluding the ones seen in training data
or_patho_novel=data.frame(gene=gene_list)
th=0.8
case_freq_gene<-aggregate(case_freq~Gene,data=subset(variant_count,hrc<=th ),sum)
or_patho_novel$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$Gene),]$case_freq
or_patho_novel$case_freq_gene<-ifelse(is.na(or_patho_novel$case_freq_gene),0,or_patho_novel$case_freq_gene)

gnomAD_freq_gene<-aggregate(gnomAD_AF~Gene,data=subset(gnomad_count,hrc<=th),sum)
or_patho_novel$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$Gene),]$gnomAD_AF
or_patho_novel$gnomAD_freq_gene<-ifelse(is.na(or_patho_novel$gnomAD_freq_gene),0,or_patho_novel$gnomAD_freq_gene)


or_patho_novel[or_patho_novel$gene=="ACTC1",]$gnomAD_freq_gene=1/(2*gnomAD_number)
or_patho_novel[or_patho_novel$gene=="ACTC1",]$case_freq_gene=or_patho_novel[or_patho_novel$gene=="ACTC1",]$case_freq_gene+or_patho_novel[or_patho_novel$gene=="ACTC1",]$gnomAD_freq_gene


or_patho_novel$or<-ifelse((or_patho_novel$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,or(or_patho_novel$case_freq_gene,or_patho_novel$gnomAD_freq_gene))

or_patho_novel$ci_lower<-ifelse((or_patho_novel$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,or_ci_lower(or_patho_novel$case_freq_gene,or_patho_novel$gnomAD_freq_gene,patient_number,gnomAD_number))

or_patho_novel$ci_upper<-ifelse((or_patho_novel$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,or_ci_upper(or_patho_novel$case_freq_gene,or_patho_novel$gnomAD_freq_gene,patient_number,gnomAD_number))


or_patho_novel$log_or<-ifelse((or_patho_novel$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,log(or(or_patho_novel$case_freq_gene,or_patho_novel$gnomAD_freq_gene)))

or_patho_novel$se_log_or<-ifelse((or_patho_novel$case_freq_gene==0|or_raw$gnomAD_freq_gene==0),NA,se_log_or(or_patho_novel$case_freq_gene,or_patho_novel$gnomAD_freq_gene,patient_number,gnomAD_number))

```

## Calculate the OR when using HMC < 1 to classify pathogenic variants

```{r nomially constrained_novel, include=FALSE}
## or with pathogenicity pathogenic prediction excluding the ones seen in training data
or_patho_novel_nom=data.frame(gene=gene_list)
th=1
case_freq_gene<-aggregate(case_freq~Gene,data=subset(variant_count,hrc<th),sum)
or_patho_novel_nom$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$Gene),]$case_freq
or_patho_novel_nom$case_freq_gene<-ifelse(is.na(or_patho_novel_nom$case_freq_gene),0,or_patho_novel_nom$case_freq_gene)

gnomAD_freq_gene<-aggregate(gnomAD_AF~Gene,data=subset(gnomad_count,hrc<th),sum)
or_patho_novel_nom$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$Gene),]$gnomAD_AF
or_patho_novel_nom$gnomAD_freq_gene<-ifelse(is.na(or_patho_novel_nom$gnomAD_freq_gene),0,or_patho_novel_nom$gnomAD_freq_gene)

or_patho_novel_nom[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(or_patho_novel_nom[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2],predict = "pathogenic")}))
or_patho_novel_nom[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(or_patho_novel_nom[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2],predict = "pathogenic")}))

or_patho_novel_nom$or<-or(or_patho_novel_nom$case_freq_gene,or_patho_novel_nom$gnomAD_freq_gene)

or_patho_novel_nom$ci_lower<-or_ci_lower(or_patho_novel_nom$case_freq_gene,or_patho_novel_nom$gnomAD_freq_gene,patient_number,gnomAD_number)
or_patho_novel_nom$ci_upper<-or_ci_upper(or_patho_novel_nom$case_freq_gene,or_patho_novel_nom$gnomAD_freq_gene,patient_number,gnomAD_number)


or_patho_novel_nom$log_or<-log(or(or_patho_novel_nom$case_freq_gene,or_patho_novel_nom$gnomAD_freq_gene))

or_patho_novel_nom$se_log_or<-se_log_or(or_patho_novel_nom$case_freq_gene,or_patho_novel_nom$gnomAD_freq_gene,patient_number,gnomAD_number)


```

## Calculate ORs for HMC unconstrained variants

```{r benign_novel, include=FALSE}
## or with pathogenicity pathogenic prediction excluding the ones seen in training data
or_benign_novel=data.frame(gene=gene_list)

th=1
case_freq_gene<-aggregate(case_freq~Gene,data=subset(variant_count,hrc>th ),sum)
or_benign_novel$case_freq_gene<-case_freq_gene[match(gene_list,case_freq_gene$Gene),]$case_freq
or_benign_novel$case_freq_gene<-ifelse(is.na(or_benign_novel$case_freq_gene),0,or_benign_novel$case_freq_gene)

gnomAD_freq_gene<-aggregate(gnomAD_AF~Gene,data=subset(gnomad_count,hrc>th),sum)
or_benign_novel$gnomAD_freq_gene<-gnomAD_freq_gene[match(gene_list,gnomAD_freq_gene$Gene),]$gnomAD_AF
or_benign_novel$gnomAD_freq_gene<-ifelse(is.na(or_benign_novel$gnomAD_freq_gene),0,or_benign_novel$gnomAD_freq_gene)

or_benign_novel[,c("case_freq_gene","gnomAD_freq_gene")]=t(apply(or_benign_novel[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){check_input(x[1],x[2],predict = "benign")}))

or_benign_novel$or<-apply(or_benign_novel[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){or(x[1],x[2],predict="benign")})
  
or_benign_novel$ci_lower<-apply(or_benign_novel[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){or_ci_lower(x[1],x[2],patient_number,gnomAD_number,predict="benign")})
or_benign_novel$ci_upper<-apply(or_benign_novel[,c("case_freq_gene","gnomAD_freq_gene")],1,function(x){or_ci_upper(x[1],x[2],patient_number,gnomAD_number,predict="benign")})

or_benign_novel$log_or<-log(or(or_benign_novel$case_freq_gene,or_benign_novel$gnomAD_freq_gene))

or_benign_novel$se_log_or<-se_log_or(or_benign_novel$case_freq_gene,or_benign_novel$gnomAD_freq_gene,patient_number,gnomAD_number)

```

# Forest plot
```{r}
or_raw$class="All(Unclassified)"
or_patho_novel$class="Highly constrained\n(HRC<0.8)"
or_patho_novel_nom$class="Constrained\n(HRC<1)"
or_benign_novel$class="Unconstrained\n(HRC>=1)"

or<-rbind(or_raw,or_patho_novel,or_patho_novel_nom,or_benign_novel)
or<-subset(or,is.element(gene,sarc_gene))
or

or$class<-factor(or$class,levels=c("All(Unclassified)","Highly constrained\n(HRC<0.8)","Constrained\n(HRC<1)","Unconstrained\n(HRC>=1)"))
or$gene<-factor(or$gene,levels=c("MYBPC3","MYH7","ACTC1","MYL2"))

or$lg10<-log10(exp(or$log_or))
or$lg10_l<-log10(exp(or$log_or-1.96*or$se_log_or))
or$lg10_u<-log10(exp(or$log_or+1.96*or$se_log_or))

library(ggplot2)
pd = position_dodge(.5) 
ggplot(or,aes(x=gene,y=lg10,color=class))+geom_hline(yintercept=0, linetype="dashed", color = "red")+geom_point(shape=16,size=3,position=pd)+geom_errorbar(aes(ymin=lg10_l,ymax=lg10_u),width=0.3,size=0.8,position=pd)+ylab("OR")+xlab("Sarcomere Genes")+theme_classic(base_size =13)+scale_color_manual(values=c("#999999", "#B2182B","#f37735","#2166AC"))+theme(axis.text.x = element_text(face = "italic"))+scale_y_continuous(labels = c(-10,1,10,100,1000,10000))
```

